/**
 * Search Index Content
 * Content aggregated from Black-owned sources, creators, and hashtag discovery
 */

export interface SearchResult {
  id: string;
  title: string;
  description: string;
  url: string;
  source: string;
  creator?: string;
  category: string;
  tags: string[];
  isBlackOwned: boolean;
  publishedAt: string;
}

export const searchContent: SearchResult[] = [
  // ==================== HAIR ====================
  {
    id: "h1",
    title: "The Ultimate Guide to Protective Styles for Natural Hair",
    description: "From box braids to faux locs, discover protective styles that promote hair growth while keeping your crown looking gorgeous.",
    category: "hair",
    source: "ESSENCE",
    creator: "Maya Johnson",
    url: "https://essence.com/hair/protective-styles-guide",
    tags: ["protective styles", "natural hair", "box braids", "4c", "4b", "braids", "#protectivestyles", "#naturalhairdaily"],
    isBlackOwned: true,
    publishedAt: "2024-10-08",
  },
  {
    id: "h2",
    title: "LOC Method: Maximum Moisture for Type 4 Hair",
    description: "The Liquid-Oil-Cream method for moisture retention. Perfect for 4A, 4B, and 4C hair textures that need extra hydration.",
    category: "hair",
    source: "Black Girl Long Hair",
    creator: "Destiny Williams",
    url: "https://blackgirllonghair.com/loc-method",
    tags: ["LOC method", "4c hair", "4b hair", "4a hair", "moisture", "type 4", "#4chair", "#locmethod"],
    isBlackOwned: true,
    publishedAt: "2024-10-07",
  },
  {
    id: "h3",
    title: "3B Hair Care: Define Those Curls",
    description: "Everything about 3B hair - springy curls that need the right products. Gel vs cream, diffusing tips, and combos that work.",
    category: "hair",
    source: "CurlPattern",
    creator: "Jasmine Cole",
    url: "https://curlpattern.com/3b-hair-guide",
    tags: ["3b hair", "3b", "curly hair", "curl definition", "type 3", "#3bhair", "#curlyhair"],
    isBlackOwned: true,
    publishedAt: "2024-10-06",
  },
  {
    id: "h4",
    title: "Type 3 Curls: Understanding 3A, 3B, and 3C",
    description: "The complete breakdown of Type 3 hair patterns. How to identify yours and care for each curl type.",
    category: "hair",
    source: "Un-ruly",
    url: "https://un-ruly.com/type-3-guide",
    tags: ["3a", "3b", "3c", "type 3", "curly hair", "curl pattern", "#type3hair"],
    isBlackOwned: true,
    publishedAt: "2024-10-05",
  },
  {
    id: "h5",
    title: "Wash Day Routine for Low Porosity Hair",
    description: "Low porosity hair needs heat to open cuticles. Here's the full wash day routine for maximum absorption.",
    category: "hair",
    source: "Naptural85",
    creator: "Whitney White",
    url: "https://youtube.com/naptural85/low-porosity",
    tags: ["low porosity", "wash day", "natural hair", "4c", "4b", "#washdayroutine", "#lowporosityhair"],
    isBlackOwned: true,
    publishedAt: "2024-10-05",
  },
  {
    id: "h6",
    title: "Best Edge Control Products - No Flaking",
    description: "Tested 15 edge controls on humidity days. Here's what actually holds without the white residue.",
    category: "hair",
    source: "TikTok",
    creator: "@naturalneiicey",
    url: "https://tiktok.com/@naturalneiicey/edges",
    tags: ["edges", "edge control", "baby hairs", "#edgecontrol", "#laidellas", "#edges"],
    isBlackOwned: true,
    publishedAt: "2024-10-09",
  },
  {
    id: "h7",
    title: "Silk Press at Home Without Heat Damage",
    description: "Step-by-step silk press tutorial. The tools, heat settings, and products for salon results at home.",
    category: "hair",
    source: "Instagram",
    creator: "@lacyredway",
    url: "https://instagram.com/lacyredway/silkpress",
    tags: ["silk press", "straightening", "heat styling", "#silkpress", "#naturalhairsilkpress"],
    isBlackOwned: true,
    publishedAt: "2024-10-08",
  },
  {
    id: "h8",
    title: "Starter Locs: Month by Month Journey",
    description: "What to expect your first year of locs. The ugly stage is real but here's how to get through it.",
    category: "hair",
    source: "TikTok",
    creator: "@lydiaturner_",
    url: "https://tiktok.com/@lydiaturner_/locjourney",
    tags: ["locs", "starter locs", "loc journey", "#locjourney", "#starterlocs", "#locstyles"],
    isBlackOwned: true,
    publishedAt: "2024-10-07",
  },
  {
    id: "h9",
    title: "4C Hair Shrinkage: Work With It, Not Against It",
    description: "Shrinkage means your hair is healthy. Here's how to stretch without heat and show your real length.",
    category: "hair",
    source: "EBONY",
    url: "https://ebony.com/hair/4c-shrinkage",
    tags: ["4c hair", "shrinkage", "natural hair", "4c", "#4chair", "#shrinkage", "#naturalhair"],
    isBlackOwned: true,
    publishedAt: "2024-10-04",
  },
  {
    id: "h10",
    title: "Braid Maintenance: Keep Your Style Fresh",
    description: "Make your braids last 6-8 weeks. Night routine, edge care, and when to take them out.",
    category: "hair",
    source: "Black Girl Long Hair",
    url: "https://blackgirllonghair.com/braid-maintenance",
    tags: ["braids", "box braids", "protective styles", "#boxbraids", "#braidstyles", "#knotlessbraids"],
    isBlackOwned: true,
    publishedAt: "2024-10-03",
  },
  {
    id: "h11",
    title: "The Best Leave-In Conditioners for Natural Hair",
    description: "From drugstore to high-end, the leave-ins that actually work for textured hair. Tested on 3A to 4C.",
    category: "hair",
    source: "21Ninety",
    url: "https://21ninety.com/best-leave-ins",
    tags: ["leave-in", "conditioner", "natural hair", "3b", "3c", "4a", "4b", "4c", "#naturalhairproducts"],
    isBlackOwned: true,
    publishedAt: "2024-10-02",
  },
  {
    id: "h12",
    title: "Twist Out vs Braid Out: Which Is Better?",
    description: "The eternal debate. When to choose twists, when to choose braids, and techniques for both.",
    category: "hair",
    source: "CurlPattern",
    url: "https://curlpattern.com/twist-vs-braid",
    tags: ["twist out", "braid out", "styling", "natural hair", "#twistout", "#braidout", "#naturalhairroutine"],
    isBlackOwned: true,
    publishedAt: "2024-10-01",
  },

  // ==================== BEAUTY ====================
  {
    id: "b1",
    title: "Foundation Matching for Deep Skin Tones",
    description: "Stop getting ashy foundation. Guide to undertones (olive, red, golden) and brands with actual range.",
    category: "beauty",
    source: "Cocoa Swatches",
    creator: "Nia Davis",
    url: "https://cocoaswatches.com/foundation-matching",
    tags: ["foundation", "dark skin", "makeup", "undertones", "#melaninmakeup", "#darkskinfoundation"],
    isBlackOwned: true,
    publishedAt: "2024-10-09",
  },
  {
    id: "b2",
    title: "Fenty vs Danessa Myricks vs Pat McGrath: The Deep Shade Test",
    description: "Comparing the top foundations for deep skin. Coverage, oxidation, lasting power, and value.",
    category: "beauty",
    source: "Instagram",
    creator: "@jackieaina",
    url: "https://instagram.com/jackieaina/foundation-test",
    tags: ["foundation", "Fenty", "dark skin", "#foundationreview", "#fentybeauty", "#darkskinmakeup"],
    isBlackOwned: true,
    publishedAt: "2024-10-08",
  },
  {
    id: "b3",
    title: "Skincare for Hyperpigmentation: What Actually Fades Dark Spots",
    description: "Dermatologist-backed ingredients for melanin skin. Vitamin C, niacinamide, and what to avoid.",
    category: "beauty",
    source: "BlackDoctor.org",
    url: "https://blackdoctor.org/hyperpigmentation-skincare",
    tags: ["skincare", "dark spots", "hyperpigmentation", "melanin", "#skincareroutine", "#hyperpigmentation"],
    isBlackOwned: true,
    publishedAt: "2024-10-07",
  },
  {
    id: "b4",
    title: "Sunscreen Without the White Cast",
    description: "Finally, sunscreens that work on dark skin. Chemical vs mineral, and the ones that disappear.",
    category: "beauty",
    source: "TikTok",
    creator: "@skinbyduby",
    url: "https://tiktok.com/@skinbyduby/sunscreen",
    tags: ["sunscreen", "SPF", "dark skin", "no white cast", "#blackgirlsunscreen", "#spf"],
    isBlackOwned: true,
    publishedAt: "2024-10-06",
  },
  {
    id: "b5",
    title: "Bold Lip Colors That Pop on Melanin Skin",
    description: "From berry to orange to classic red - lip colors that complement dark skin tones with swatches.",
    category: "beauty",
    source: "Cocoa Swatches",
    url: "https://cocoaswatches.com/bold-lips",
    tags: ["lipstick", "dark skin", "makeup", "bold lips", "#melaninlips", "#lipswatches"],
    isBlackOwned: true,
    publishedAt: "2024-10-05",
  },
  {
    id: "b6",
    title: "Color Correcting for Dark Under Eyes",
    description: "Orange, peach, or red corrector? Depends on your depth. Here's how to find your match.",
    category: "beauty",
    source: "TikTok",
    creator: "@sheilamei",
    url: "https://tiktok.com/@sheilamei/color-correct",
    tags: ["concealer", "dark circles", "color correcting", "#colorcorrecting", "#undereyes"],
    isBlackOwned: true,
    publishedAt: "2024-10-04",
  },
  {
    id: "b7",
    title: "Skincare Routine for Oily Melanin Skin",
    description: "Control shine without stripping your skin. Morning and night routine for oily textured skin.",
    category: "beauty",
    source: "Instagram",
    creator: "@brownskingirlsrock",
    url: "https://instagram.com/brownskingirlsrock/oily-skin",
    tags: ["skincare", "oily skin", "melanin", "#skincareroutine", "#oilyskincare"],
    isBlackOwned: true,
    publishedAt: "2024-10-03",
  },
  {
    id: "b8",
    title: "Black-Owned Beauty Brands Worth Your Money",
    description: "From Fenty to indie brands - Black-owned makeup and skincare that actually performs.",
    category: "beauty",
    source: "ESSENCE",
    url: "https://essence.com/beauty/black-owned-brands",
    tags: ["Black-owned", "beauty brands", "makeup", "#supportblackowned", "#blackownedbeauty"],
    isBlackOwned: true,
    publishedAt: "2024-10-02",
  },

  // ==================== FASHION ====================
  {
    id: "f1",
    title: "Black Designers Dominating Fashion Week",
    description: "From Telfar to LaQuan Smith to Theophilio - Black designers making runway history.",
    category: "fashion",
    source: "EBONY",
    url: "https://ebony.com/fashion/black-designers-2024",
    tags: ["fashion", "designers", "Telfar", "runway", "#blackdesigners", "#fashionweek"],
    isBlackOwned: true,
    publishedAt: "2024-10-09",
  },
  {
    id: "f2",
    title: "How to Style Ankara in 2024",
    description: "Modern ways to wear African print. Office appropriate, weekend casual, and evening looks.",
    category: "fashion",
    source: "21Ninety",
    creator: "Amara Okonkwo",
    url: "https://21ninety.com/ankara-styling",
    tags: ["Ankara", "African print", "fashion", "style", "#ankarastyles", "#africanfashion"],
    isBlackOwned: true,
    publishedAt: "2024-10-08",
  },
  {
    id: "f3",
    title: "The Telfar Bag: Why It Became a Cultural Symbol",
    description: "How Telfar Clemens made luxury accessible. The bag's journey from Bushwick to everywhere.",
    category: "fashion",
    source: "The Root",
    url: "https://theroot.com/telfar-bag-history",
    tags: ["Telfar", "fashion", "Black-owned", "bags", "#telfar", "#bushwickbirkin"],
    isBlackOwned: true,
    publishedAt: "2024-10-07",
  },
  {
    id: "f4",
    title: "Streetwear Brands by Black Designers",
    description: "Beyond the mainstream - Black-owned streetwear labels you should know.",
    category: "fashion",
    source: "Okayplayer",
    url: "https://okayplayer.com/streetwear-black-designers",
    tags: ["streetwear", "fashion", "Black-owned", "designers", "#streetwear", "#blackownedfashion"],
    isBlackOwned: true,
    publishedAt: "2024-10-06",
  },
  {
    id: "f5",
    title: "Fall Outfit Ideas: TikTok Edition",
    description: "The best fall fits from Black fashion creators on TikTok. Affordable to luxury.",
    category: "fashion",
    source: "TikTok",
    creator: "@wisdm",
    url: "https://tiktok.com/@wisdm/fall-outfits",
    tags: ["fall fashion", "outfits", "style", "#falloutfits", "#blackfashion", "#ootd"],
    isBlackOwned: true,
    publishedAt: "2024-10-05",
  },
  {
    id: "f6",
    title: "Modest Fashion for Every Occasion",
    description: "Stylish covered looks - hijabi fashion, long skirts, and elevated modest styling.",
    category: "fashion",
    source: "Instagram",
    creator: "@blackwomeninluxury",
    url: "https://instagram.com/blackwomeninluxury/modest",
    tags: ["modest fashion", "hijab", "fashion", "style", "#modestfashion", "#blackhijabi"],
    isBlackOwned: true,
    publishedAt: "2024-10-04",
  },

  // ==================== CULTURE ====================
  {
    id: "c1",
    title: "Juneteenth 2024: How Communities Are Celebrating",
    description: "Events, traditions, and the ongoing fight for recognition. How Juneteenth is honored nationwide.",
    category: "culture",
    source: "The Root",
    url: "https://theroot.com/juneteenth-2024",
    tags: ["Juneteenth", "history", "culture", "freedom", "#juneteenth", "#blackhistory"],
    isBlackOwned: true,
    publishedAt: "2024-06-19",
  },
  {
    id: "c2",
    title: "Black Museums and Cultural Centers to Visit",
    description: "From the Smithsonian NMAAHC to local gems - Black history and art institutions across America.",
    category: "culture",
    source: "EBONY",
    url: "https://ebony.com/black-museums-guide",
    tags: ["museums", "Black history", "culture", "art", "#blackmuseums", "#nmaahc"],
    isBlackOwned: true,
    publishedAt: "2024-10-08",
  },
  {
    id: "c3",
    title: "Black Travel: Destination Guide for Solo Travelers",
    description: "Safe and welcoming destinations for Black solo travelers. Tips from experienced globetrotters.",
    category: "culture",
    source: "Instagram",
    creator: "@blacktravelbox",
    url: "https://instagram.com/blacktravelbox/solo-travel",
    tags: ["travel", "solo travel", "Black travel", "#blacktravel", "#solotravel", "#travelingwhileblack"],
    isBlackOwned: true,
    publishedAt: "2024-10-07",
  },
  {
    id: "c4",
    title: "Best Black-Owned Restaurants in Major Cities",
    description: "From soul food to fine dining - Black-owned restaurants worth the trip in NYC, LA, ATL, Chicago.",
    category: "culture",
    source: "Instagram",
    creator: "@blackfoodie",
    url: "https://instagram.com/blackfoodie/restaurants",
    tags: ["restaurants", "Black-owned", "food", "dining", "#blackowned", "#soulfood", "#blackfoodie"],
    isBlackOwned: true,
    publishedAt: "2024-10-06",
  },

  // ==================== BUSINESS ====================
  {
    id: "bus1",
    title: "Grants for Black Entrepreneurs in 2024",
    description: "Non-dilutive funding opportunities specifically for Black-owned businesses. Application tips included.",
    category: "business",
    source: "Black Enterprise",
    url: "https://blackenterprise.com/grants-2024",
    tags: ["grants", "entrepreneur", "funding", "business", "#blackbusiness", "#entrepreneurship"],
    isBlackOwned: true,
    publishedAt: "2024-10-09",
  },
  {
    id: "bus2",
    title: "Black-Owned Banks: Where to Move Your Money",
    description: "Financial institutions owned by and serving the Black community. Full directory with offerings.",
    category: "business",
    source: "Blavity",
    url: "https://blavity.com/black-owned-banks",
    tags: ["banking", "finance", "Black-owned", "#bankblack", "#blackwealthmatters"],
    isBlackOwned: true,
    publishedAt: "2024-10-08",
  },
  {
    id: "bus3",
    title: "Building Generational Wealth: Investment Basics",
    description: "Stocks, real estate, index funds - practical investing advice for building family wealth.",
    category: "business",
    source: "Instagram",
    creator: "@melaninmoney",
    url: "https://instagram.com/melaninmoney/investing",
    tags: ["investing", "wealth", "finance", "#generationalwealth", "#blackwealth", "#investing101"],
    isBlackOwned: true,
    publishedAt: "2024-10-07",
  },

  // ==================== WEB3 ====================
  {
    id: "w1",
    title: "Bitcoin & Black America: The Case for Crypto",
    description: "How cryptocurrency addresses systemic financial exclusion. A practical guide to getting started.",
    category: "web3",
    source: "Bitcoin & Black America",
    creator: "Isaiah Jackson",
    url: "https://bitcoinandblackamerica.com",
    tags: ["bitcoin", "crypto", "finance", "web3", "#bitcoin", "#cryptofortheculture"],
    isBlackOwned: true,
    publishedAt: "2024-10-09",
  },
  {
    id: "w2",
    title: "Black NFT Artists Making Waves",
    description: "Digital artists creating NFT work that matters. Afrofuturism, portraits, and abstract pieces.",
    category: "web3",
    source: "AfroTech",
    url: "https://afrotech.com/black-nft-artists",
    tags: ["NFT", "digital art", "artists", "web3", "#nftart", "#blacknftartist", "#afrofuturism"],
    isBlackOwned: true,
    publishedAt: "2024-10-08",
  },
  {
    id: "w3",
    title: "Getting Started with Crypto: Beginner Guide",
    description: "No jargon, just practical steps. How to buy your first Bitcoin and store it safely.",
    category: "web3",
    source: "Black Bitcoin Billionaire",
    url: "https://blackbitcoinbillionaire.com/start",
    tags: ["crypto", "beginner", "bitcoin", "web3", "#cryptobeginners", "#buybitcoin"],
    isBlackOwned: true,
    publishedAt: "2024-10-07",
  },

  // ==================== WELLNESS ====================
  {
    id: "well1",
    title: "Finding a Black Therapist: Directory & Tips",
    description: "Culturally competent mental health care. How to find a therapist who understands your experience.",
    category: "wellness",
    source: "Therapy for Black Girls",
    url: "https://therapyforblackgirls.com/directory",
    tags: ["mental health", "therapy", "wellness", "#blacktherapist", "#mentalhealthmatters"],
    isBlackOwned: true,
    publishedAt: "2024-10-09",
  },
  {
    id: "well2",
    title: "Black Fitness Creators to Follow",
    description: "Trainers and fitness influencers making space for all body types. Workouts, motivation, community.",
    category: "wellness",
    source: "ESSENCE",
    url: "https://essence.com/wellness/black-fitness-creators",
    tags: ["fitness", "workout", "wellness", "#blackfitness", "#fitnessmotivation"],
    isBlackOwned: true,
    publishedAt: "2024-10-08",
  },
  {
    id: "well3",
    title: "Managing Stress: Practices That Actually Work",
    description: "Beyond bubble baths - practical stress management for Black women dealing with everything.",
    category: "wellness",
    source: "For Harriet",
    url: "https://forharriet.com/stress-management",
    tags: ["stress", "wellness", "mental health", "self-care", "#blackwomenhealth", "#selfcare"],
    isBlackOwned: true,
    publishedAt: "2024-10-07",
  },
];

// Popular hashtags for discovery
export const popularHashtags = {
  hair: ["#naturalhairdaily", "#4chair", "#4bhair", "#3bhair", "#protectivestyles", "#washdayroutine", "#locjourney", "#twistout", "#silkpress", "#naturalhaircommunity"],
  beauty: ["#melaninmakeup", "#darkskinfoundation", "#blackgirlmakeup", "#melaninpoppin", "#blackgirlsunscreen", "#darkskinbeauty"],
  fashion: ["#blackfashion", "#ankarastyles", "#telfar", "#blackdesigners", "#africanfashion", "#blackownedfashion"],
  culture: ["#blackexcellence", "#blackhistory", "#juneteenth", "#blacktravel", "#blackfoodie", "#supportblackowned"],
  business: ["#blackbusiness", "#blackentrepreneur", "#bankblack", "#blackwealthmatters", "#generationalwealth"],
  web3: ["#cryptofortheculture", "#blacknftartist", "#bitcoin", "#afrofuturism", "#web3"],
  wellness: ["#blackmentalhealth", "#blacktherapist", "#blackfitness", "#selfcare", "#blackwomenhealth"],
};
