import { SearchableContent, ContentSource, Creator } from "./ranking";

/**
 * VERIFIED SOURCES DATABASE
 * These are sources that have been verified as Black-owned or Black-created
 */
export const verifiedSources: Record<string, ContentSource> = {
  naturally_curly: {
    id: "src_001",
    name: "NaturallyCurly",
    url: "https://naturallycurly.com",
    verificationLevel: "editorial",
    isBlackOwned: false,
    isBlackCreated: true, // Many Black contributors
    communityScore: 92,
    qualityScore: 88,
  },
  curl_pattern: {
    id: "src_002",
    name: "CurlPattern",
    url: "https://curlpattern.com",
    verificationLevel: "editorial",
    isBlackOwned: true,
    isBlackCreated: true,
    communityScore: 95,
    qualityScore: 90,
  },
  loc_love: {
    id: "src_003",
    name: "LocLove Magazine",
    url: "https://loclovemag.com",
    verificationLevel: "editorial",
    isBlackOwned: true,
    isBlackCreated: true,
    communityScore: 88,
    qualityScore: 85,
  },
  melanin_hair: {
    id: "src_004",
    name: "MelaninHairCare",
    url: "https://melaninhaircare.com",
    verificationLevel: "editorial",
    isBlackOwned: true,
    isBlackCreated: true,
    communityScore: 91,
    qualityScore: 87,
  },
  cocoa_swatches: {
    id: "src_005",
    name: "Cocoa Swatches",
    url: "https://cocoaswatches.com",
    verificationLevel: "editorial",
    isBlackOwned: true,
    isBlackCreated: true,
    communityScore: 94,
    qualityScore: 92,
  },
  melanin_glow: {
    id: "src_006",
    name: "MelaninGlow",
    url: "https://melaninglow.com",
    verificationLevel: "community",
    isBlackOwned: true,
    isBlackCreated: true,
    communityScore: 86,
    qualityScore: 84,
  },
  style_noir: {
    id: "src_007",
    name: "StyleNoir",
    url: "https://stylenoir.com",
    verificationLevel: "editorial",
    isBlackOwned: true,
    isBlackCreated: true,
    communityScore: 89,
    qualityScore: 88,
  },
  afro_chic: {
    id: "src_008",
    name: "AfroChic",
    url: "https://afrochic.com",
    verificationLevel: "community",
    isBlackOwned: true,
    isBlackCreated: true,
    communityScore: 87,
    qualityScore: 85,
  },
  black_history_365: {
    id: "src_009",
    name: "BlackHistory365",
    url: "https://blackhistory365.com",
    verificationLevel: "editorial",
    isBlackOwned: true,
    isBlackCreated: true,
    communityScore: 93,
    qualityScore: 91,
  },
  therapy_for_us: {
    id: "src_010",
    name: "Therapy for Us",
    url: "https://therapyforus.com",
    verificationLevel: "editorial",
    isBlackOwned: true,
    isBlackCreated: true,
    communityScore: 96,
    qualityScore: 94,
  },
};

/**
 * VERIFIED CREATORS
 */
export const verifiedCreators: Record<string, Creator> = {
  maya_johnson: {
    id: "creator_001",
    name: "Maya Johnson",
    isVerified: true,
    verificationLevel: "editorial",
    followerCount: 245000,
    contentCount: 156,
    communityRating: 4.9,
  },
  destiny_williams: {
    id: "creator_002",
    name: "Destiny Williams",
    isVerified: true,
    verificationLevel: "editorial",
    followerCount: 189000,
    contentCount: 203,
    communityRating: 4.8,
  },
  marcus_thompson: {
    id: "creator_003",
    name: "Marcus Thompson",
    isVerified: true,
    verificationLevel: "community",
    followerCount: 78000,
    contentCount: 89,
    communityRating: 4.7,
  },
  nia_davis: {
    id: "creator_004",
    name: "Nia Davis",
    isVerified: true,
    verificationLevel: "editorial",
    followerCount: 312000,
    contentCount: 267,
    communityRating: 4.9,
  },
  keisha_brown: {
    id: "creator_005",
    name: "Keisha Brown",
    isVerified: true,
    verificationLevel: "editorial",
    followerCount: 156000,
    contentCount: 134,
    communityRating: 4.8,
  },
  amara_okonkwo: {
    id: "creator_006",
    name: "Amara Okonkwo",
    isVerified: true,
    verificationLevel: "editorial",
    followerCount: 98000,
    contentCount: 78,
    communityRating: 4.9,
  },
};

/**
 * CONTENT DATABASE
 * In production, this would be a real database with millions of entries
 */
export const contentDatabase: SearchableContent[] = [
  // ========== HAIR CONTENT ==========
  {
    id: "content_001",
    title: "The Ultimate Guide to Protective Styles for Natural Hair",
    description: "From box braids to faux locs, discover protective styles that promote hair growth while keeping your crown looking gorgeous. This comprehensive guide covers installation tips, maintenance routines, and how to keep your natural hair healthy underneath. Expert tips from licensed stylists who specialize in textured hair.",
    url: "https://curlpattern.com/protective-styles-guide",
    source: verifiedSources.curl_pattern,
    creator: verifiedCreators.maya_johnson,
    category: "hair",
    tags: ["protective styles", "box braids", "faux locs", "natural hair", "hair growth", "4c hair"],
    publishedAt: new Date("2024-09-15"),
    communityUpvotes: 2847,
    communityFlags: 0,
    viewCount: 156000,
    saveCount: 8934,
    submittedBy: "editorial",
  },
  {
    id: "content_002",
    title: "LOC Method: The Secret to Moisturized Type 4 Hair",
    description: "Learn how to properly layer your products using the Liquid-Oil-Cream method for maximum moisture retention. Perfect for 4A, 4B, and 4C hair textures. Includes product recommendations and step-by-step tutorials with video demonstrations.",
    url: "https://curlpattern.com/loc-method",
    source: verifiedSources.curl_pattern,
    creator: verifiedCreators.destiny_williams,
    category: "hair",
    tags: ["LOC method", "moisture", "4c hair", "4b hair", "4a hair", "natural hair care"],
    publishedAt: new Date("2024-10-01"),
    communityUpvotes: 3201,
    communityFlags: 0,
    viewCount: 189000,
    saveCount: 12456,
    submittedBy: "editorial",
  },
  {
    id: "content_003",
    title: "Loc Maintenance 101: From Starter Locs to Mature",
    description: "Everything you need to know about starting and maintaining locs at every stage. Comprehensive guide covering washing techniques, retwisting schedules, and styling tips from loc journey veterans. Real talk about the commitment and the beautiful results.",
    url: "https://loclovemag.com/loc-maintenance-guide",
    source: verifiedSources.loc_love,
    creator: verifiedCreators.marcus_thompson,
    category: "hair",
    tags: ["locs", "dreadlocks", "loc maintenance", "starter locs", "retwisting", "loc journey"],
    publishedAt: new Date("2024-08-20"),
    communityUpvotes: 1876,
    communityFlags: 0,
    viewCount: 98000,
    saveCount: 5623,
    submittedBy: "verified_creator",
  },
  {
    id: "content_004",
    title: "Best Edge Control Products for Sleek Laid Baby Hairs",
    description: "Comprehensive review of edge control products that hold without flaking. We tested 25 products across different humidity levels and hair textures. Includes options for sensitive scalps and products that won't cause buildup or damage your edges.",
    url: "https://melaninhaircare.com/edge-control-review",
    source: verifiedSources.melanin_hair,
    category: "hair",
    tags: ["edges", "baby hairs", "edge control", "laid edges", "product review"],
    publishedAt: new Date("2024-09-28"),
    communityUpvotes: 2234,
    communityFlags: 0,
    viewCount: 134000,
    saveCount: 7891,
    submittedBy: "editorial",
  },
  {
    id: "content_005",
    title: "Silk Press vs. Keratin Treatment: What's Better for Your Hair?",
    description: "A detailed comparison of temporary and semi-permanent straightening methods. We break down the pros, cons, damage potential, and maintenance for each. Plus heat protection tips and recovery routines to keep your curls bouncing back.",
    url: "https://naturallycurly.com/silk-press-vs-keratin",
    source: verifiedSources.naturally_curly,
    creator: verifiedCreators.keisha_brown,
    category: "hair",
    tags: ["silk press", "keratin treatment", "heat styling", "natural hair", "straightening"],
    publishedAt: new Date("2024-09-10"),
    communityUpvotes: 1654,
    communityFlags: 0,
    viewCount: 87000,
    saveCount: 4532,
    submittedBy: "verified_creator",
  },
  {
    id: "content_006",
    title: "Wash Day Routine for Low Porosity Hair",
    description: "Low porosity hair needs special attention. Learn how to open up those cuticles for maximum moisture absorption, the best clarifying shampoos, and deep conditioning techniques that actually work. Includes product recommendations under $20.",
    url: "https://curlpattern.com/low-porosity-wash-day",
    source: verifiedSources.curl_pattern,
    creator: verifiedCreators.destiny_williams,
    category: "hair",
    tags: ["low porosity", "wash day", "deep conditioning", "natural hair", "hair care routine"],
    publishedAt: new Date("2024-10-05"),
    communityUpvotes: 1987,
    communityFlags: 0,
    viewCount: 76000,
    saveCount: 5234,
    submittedBy: "editorial",
  },

  // ========== BEAUTY CONTENT ==========
  {
    id: "content_007",
    title: "Foundation Matching for Deep Skin Tones: A Complete Guide",
    description: "Find your perfect foundation match with our comprehensive guide to undertones, formulas, and the best brands for melanin-rich skin. We swatch 50+ foundations on various deep skin tones so you can see real results before you buy.",
    url: "https://cocoaswatches.com/foundation-guide",
    source: verifiedSources.cocoa_swatches,
    creator: verifiedCreators.nia_davis,
    category: "beauty",
    tags: ["foundation", "deep skin", "dark skin makeup", "undertones", "melanin"],
    publishedAt: new Date("2024-09-20"),
    communityUpvotes: 4521,
    communityFlags: 0,
    viewCount: 267000,
    saveCount: 18934,
    submittedBy: "editorial",
  },
  {
    id: "content_008",
    title: "Skincare Routine for Hyperpigmentation and Dark Spots",
    description: "Dermatologist-approved ingredients and routines specifically formulated for melanin-rich skin. Learn about Vitamin C serums, niacinamide, and other ingredients that fade dark spots without causing irritation or further discoloration.",
    url: "https://melaninglow.com/hyperpigmentation-routine",
    source: verifiedSources.melanin_glow,
    category: "beauty",
    tags: ["hyperpigmentation", "dark spots", "skincare", "vitamin c", "melanin skin"],
    publishedAt: new Date("2024-09-25"),
    communityUpvotes: 3876,
    communityFlags: 0,
    viewCount: 198000,
    saveCount: 14567,
    submittedBy: "community",
  },
  {
    id: "content_009",
    title: "Bold Lip Colors That Pop on Dark Skin",
    description: "From berry tones to classic reds, discover lipstick shades that complement and enhance darker complexions beautifully. We test 40 lipsticks across multiple brands with swatches on real dark skin tones.",
    url: "https://cocoaswatches.com/bold-lips-dark-skin",
    source: verifiedSources.cocoa_swatches,
    creator: verifiedCreators.nia_davis,
    category: "beauty",
    tags: ["lipstick", "dark skin", "bold lips", "makeup", "lip color"],
    publishedAt: new Date("2024-10-02"),
    communityUpvotes: 2345,
    communityFlags: 0,
    viewCount: 145000,
    saveCount: 8765,
    submittedBy: "editorial",
  },
  {
    id: "content_010",
    title: "Sunscreen for Dark Skin: No White Cast Options",
    description: "Yes, we need sunscreen too! Here are the best sunscreens that protect without leaving that dreaded white cast. Tested by real people with dark skin, with honest reviews about texture, finish, and wear.",
    url: "https://melaninglow.com/sunscreen-no-white-cast",
    source: verifiedSources.melanin_glow,
    category: "beauty",
    tags: ["sunscreen", "dark skin", "SPF", "no white cast", "skincare"],
    publishedAt: new Date("2024-08-15"),
    communityUpvotes: 5678,
    communityFlags: 0,
    viewCount: 312000,
    saveCount: 23456,
    submittedBy: "editorial",
  },

  // ========== FASHION CONTENT ==========
  {
    id: "content_011",
    title: "Black-Owned Fashion Brands You Need to Know in 2024",
    description: "From luxury designers like Telfar and Pyer Moss to emerging streetwear labels, discover Black-owned fashion brands making waves in the industry. Includes price ranges, where to shop, and the stories behind each brand.",
    url: "https://stylenoir.com/black-owned-fashion-brands-2024",
    source: verifiedSources.style_noir,
    category: "fashion",
    tags: ["Black-owned", "fashion brands", "Telfar", "Pyer Moss", "streetwear", "luxury fashion"],
    publishedAt: new Date("2024-10-01"),
    communityUpvotes: 3456,
    communityFlags: 0,
    viewCount: 189000,
    saveCount: 12345,
    submittedBy: "editorial",
  },
  {
    id: "content_012",
    title: "African Print Fashion: Modern Ways to Style Ankara",
    description: "Contemporary styling tips for incorporating traditional African prints into your everyday wardrobe. From office-appropriate looks to weekend vibes, see how creators are blending heritage with modern fashion.",
    url: "https://afrochic.com/ankara-styling-guide",
    source: verifiedSources.afro_chic,
    creator: verifiedCreators.amara_okonkwo,
    category: "fashion",
    tags: ["Ankara", "African print", "African fashion", "styling tips", "heritage fashion"],
    publishedAt: new Date("2024-09-18"),
    communityUpvotes: 2789,
    communityFlags: 0,
    viewCount: 156000,
    saveCount: 9876,
    submittedBy: "verified_creator",
  },

  // ========== CULTURE CONTENT ==========
  {
    id: "content_013",
    title: "The History and Significance of Juneteenth",
    description: "Understanding the true meaning of Juneteenth, its historical significance, and how communities celebrate freedom today. Includes interviews with historians and coverage of celebrations across the country.",
    url: "https://blackhistory365.com/juneteenth-history",
    source: verifiedSources.black_history_365,
    category: "culture",
    tags: ["Juneteenth", "Black history", "freedom", "celebration", "American history"],
    publishedAt: new Date("2024-06-19"),
    communityUpvotes: 8765,
    communityFlags: 0,
    viewCount: 456000,
    saveCount: 34567,
    submittedBy: "editorial",
  },
  {
    id: "content_014",
    title: "Emerging Black Artists Reshaping Contemporary Art",
    description: "Meet the artists creating groundbreaking work in painting, sculpture, digital art, and mixed media across the globe. Features interviews, studio visits, and where to see their work.",
    url: "https://blackhistory365.com/emerging-black-artists",
    source: verifiedSources.black_history_365,
    category: "culture",
    tags: ["Black artists", "contemporary art", "visual art", "art scene", "emerging artists"],
    publishedAt: new Date("2024-09-05"),
    communityUpvotes: 2134,
    communityFlags: 0,
    viewCount: 87000,
    saveCount: 5678,
    submittedBy: "editorial",
  },

  // ========== WELLNESS CONTENT ==========
  {
    id: "content_015",
    title: "Mental Health Resources for the Black Community",
    description: "Culturally competent therapists, support groups, and mental health resources that understand our unique experiences. Directory of Black therapists, free and low-cost options, and tips for finding the right support.",
    url: "https://therapyforus.com/mental-health-resources",
    source: verifiedSources.therapy_for_us,
    category: "wellness",
    tags: ["mental health", "therapy", "Black therapists", "support groups", "self-care"],
    publishedAt: new Date("2024-09-30"),
    communityUpvotes: 6543,
    communityFlags: 0,
    viewCount: 345000,
    saveCount: 28765,
    submittedBy: "editorial",
  },
  {
    id: "content_016",
    title: "Navigating Therapy as a Black Person",
    description: "Real talk about finding therapists who get it, dealing with stigma in our communities, and why taking care of your mental health is an act of resistance. Personal stories and practical advice.",
    url: "https://therapyforus.com/navigating-therapy",
    source: verifiedSources.therapy_for_us,
    category: "wellness",
    tags: ["therapy", "mental health", "Black experience", "stigma", "healing"],
    publishedAt: new Date("2024-08-28"),
    communityUpvotes: 4321,
    communityFlags: 0,
    viewCount: 234000,
    saveCount: 18765,
    submittedBy: "editorial",
  },
];

/**
 * Search the content database
 */
export function searchContent(
  query: string,
  category?: string
): SearchableContent[] {
  let results = [...contentDatabase];

  // Filter by category
  if (category && category !== "all") {
    results = results.filter((item) => item.category === category);
  }

  // Filter by query
  if (query) {
    const lowerQuery = query.toLowerCase();
    results = results.filter((item) => {
      const searchableText = `${item.title} ${item.description} ${item.tags.join(" ")} ${item.source.name} ${item.creator?.name || ""}`.toLowerCase();
      return searchableText.includes(lowerQuery);
    });
  }

  return results;
}
